const DataPenerbangan = [
  [
    "Lampung",
    "Ambon",
    "Jawa",
    "pontianak",
    "Aceh",
    "Jakarta",
    "Jambi",
    "Maluku",
    "Samarinda",
    "Bandung",
    "Kalimantan",
  ],
  [
    "Lampung",
    "Bandung",
    "Ambon",
    "Jawa",
    "Samarinda",
    "Maluku",
    "Pontianak",
    "Jakarta",
    "Jambi",
    "Aceh",
    "Kalimantan",
  ],
  [
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
    "06 April 2020",
  ],
  [
    "Elang",
    "Lion Air",
    "Majapahit",
    "Elang",
    "Lion Air",
    "Majapahit",
    "Majapahit",
    "Elang",
    "Lion Air",
    "Majapahit",
  ],
];

export default DataPenerbangan;
